spring.application.name=CdacStud
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=Root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymelead.cache=false
